version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  dash:
    build:
      context: .
      dockerfile: Dockerfile
    image: headbanger84/dc-autodash
    volumes:
      # - .:/usr/src/app/
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      - "HOST=dash.docker.localhost"
    working_dir: /usr/src/app/
    labels:
      - "traefik.http.routers.dash.rule=Host(`dash.docker.localhost`)"
      - "dash.enabled=true"
      - "dash.icon.color=#AA0000"
      - "dash.icon.fa=fas fa-th-large"
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "dash.enabled=true"
      - "dash.icon.mi=public"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"